Popup window and dynamic cards feature
Rebelzob/Portfolio pull request #13
Opened 2023-06-22 20:29 UTC by Rebelzob

# Portfolio

- Complete rework of card sections in HTML file, added Javascript to populate them in the HTML dynamically.
- Added Dialog tag to HTML and worked on it for the modals.
- Added modal styling for mobile and desktop versions
- Added Javascript logic to populate modals with the cards object.

2023-06-22 20:33 UTC, GzimAsani requested changes
Hi @Rebelzob , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have commits from your pair programming partner

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-22 20:36 UTC, Rebelzob commented
@GzimAsani forgot to add to the description that **I don't have** a coding partner this week, already reported the issue to student success and they told me to work alone.

2023-06-22 20:37 UTC, GzimAsani commented
> @GzimAsani forgot to add to the description that **I don't have** a coding partner this week, already reported the issue to student success and they told me to work alone.

Please mention and add a screenshot of it

2023-06-22 20:43 UTC, Rebelzob commented
@GzimAsani This is the email I got from the student success area.
![image](https://github.com/Rebelzob/Portfolio/assets/52711805/abc6d055-060e-4ea4-b338-db2bf09c9c3a)

2023-06-22 20:44 UTC, GzimAsani commented
> @GzimAsani This is the email I got from the student success area.
> ![image](https://user-images.githubusercontent.com/52711805/248056124-abc6d055-060e-4ea4-b338-db2bf09c9c3a.png)

Great, go ahead and ask for another review

2023-06-22 21:23 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Rebelzob 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Create UIs adaptable to different screen sizes using media queries.
- ✔️ Parse a Figma design to create a UI.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 21:23 UTC, abdulhamiid commented on index.html
> +</div> -->
Please, let's not commit old pieces of code as inline comments. They will make our project look messy. If you need to review a previous version of your code, you can always use git history. 👍🤗

2023-06-22 21:23 UTC, abdulhamiid commented on js/popup.js
> +  });
Your design (Good job implementing the hover state for the project cards. 😊👍)
![image](https://github.com/Rebelzob/Portfolio/assets/78251927/021b9c37-abe8-40c3-a575-78678a4ce6f8)

Figma
![image](https://github.com/Rebelzob/Portfolio/assets/78251927/c46b9ba3-3f7f-473c-b518-59ad4941e7fe)

However, Looking at the design on [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1), it is when the user hovers over each card that the button `See Project` appears. please let's correct that. 🤗🛠

2023-06-22 22:55 UTC, Rebelzob commented on js/popup.js
> +  </div>
Hello @abdulhamiid and thanks for the review, by the way, I can see modal desktop version is different from yours in my browser 

![image](https://github.com/Rebelzob/Portfolio/assets/52711805/05625f78-a8a6-4aa0-9cec-efb4f6d524e3)

I still need to add the blur which I will, but don't know what to do about the desktop being so different yours from mine, what do you suggest?

2023-06-22 22:59 UTC, Rebelzob commented on js/popup.js
> +  </div>
also, the dialog tag is widely supported by most the browsers 

https://caniuse.com/?search=dialog

2023-06-23 00:28 UTC, Reem-lab approved these changes
# Hi Team,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights
- [ ] Great job on the funtionality for the pop up💯
- [ ] Followed GitHub flow 🔥
- [ ] No Linters error ✅
- [ ] Good job working on the design 🔥⭐

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 01:31 UTC, merged