Feature: Contact form
Rebelzob/Portfolio pull request #3
Opened 2023-06-06 22:48 UTC by Rebelzob

# Portfolio

- Added HTML and CSS form for the contact me section.
- Worked on pair programming.

2023-06-06 23:59 UTC, frempongdev requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

### Hi @Rebelzob, @MustafaSamiShirzad    👋🏼 
I'm Frempong.

You've done a great job implementing most of the requirements for this project 🚀, but there are a few changes I recommend be made. You're almost done, keep up the good work! 🤖 🎆 

<img src="https://media.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ No Linter errors. 🆗  
✅ Your project is documented well. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 
✅ Great UI. ✔️ 

 ## Required Changes ♻️
- [ ] Please check and remove the deployment section of your README as it is empty. 🗑️ 

_Kindly Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 23:59 UTC, frempongdev commented on index.html
> +          <input type="text" id="message" placeholder="Write something..." required maxlength="500">
- [ ] Great implementation of your form and its field types. 👍🏿 
However, this `message` form input should have a field `type="textarea"`. Textarea types are more appropriate for more character inputs like messages and paragraphs. 📜

2023-06-06 23:59 UTC, frempongdev commented on index.html
> +        </form>
You did a great job integrating **Formspree** in your form as an `action` in your form. 🚀 However, your form submission does not work as expected. **Formspree** requires a `name` attribute in order to match the input field.
 
![image](https://github.com/Rebelzob/Portfolio/assets/117144028/708013cf-15af-4e80-abc0-4e53b8207ef8)

- [ ] Please refer [here](https://formspree.io/html/) to check the proper implementation of **Formspree** forms. 🎯

2023-06-06 23:59 UTC, frempongdev commented on styles.css
> +    font-weight: 1000;
- [ ] Please stick to the Figma design requirements as closely as possible as it is the main essence of this module. Paying attention to details is a good trait that can go a long way to satisfy your clients in your future job. 🏢 
Below is the recommended `font weight`. 

![image](https://github.com/Rebelzob/Portfolio/assets/117144028/f5e81001-e1b7-4d2e-ac6f-f4cd24932a9d)

2023-06-07 00:55 UTC, OyePriscilla approved these changes
Hi @Rebelzob and @MustafaSamiShirzad 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Implemented forms with HTML5 validations ✔️ 
Parsed a Figma design to create a UI ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 00:55 UTC, OyePriscilla approved these changes
Hi @Rebelzob and @MustafaSamiShirzad 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Implemented forms with HTML5 validations ✔️ 
Parsed a Figma design to create a UI ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 00:58 UTC, merged